steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'src/Theatreers.Core.Tests/Theatreers.Core.Tests.csproj'
- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: pack
    packagesToPack: 'src/Theatreers.Core/Theatreers.Core.csproj'
- task: DotNetCoreCLI@2
  displayName: 'dotnet push'
  inputs:
    command: push
    publishVstsFeed: 'Theatreers.Artifacts'