variables:
  serviceName: 'show'
  tenantId: '8d56b40f-772a-4828-bf64-91905baabc85'
  projectName: 'Theatreers.Show'
  buildPublishPath: '$(Build.ArtifactStagingDirectory)/publish-path/'
  dotnetBuildOutputPath: '$(Build.ArtifactStagingDirectory)/build-output/'
stages:
- stage: 'Feature_CI_Build'
  dependsOn: []
  condition: and(succeeded(), in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI'), contains(variables['Build.SourceBranch'], 'refs/heads/feature/'))
  displayName: 'Feature CI Build'
  jobs:
    - job: 'build'
      displayName: 'Nightly Build'
      pool:
        name: Hosted Ubuntu 1604
      steps:
      # Setup the Sonar Cloud for analysis
        - task: SonarSource.sonarcloud.14d9cde6-c1da-4d55-aa01-2965cd301255.SonarCloudPrepare@1
          displayName: 'Prepare analysis on SonarCloud'
          inputs:
            SonarCloud: 'Theatreers Sonarcloud'
            organization: 'theatreers'
            projectKey: $(projectName)
            projectName: $(projectName)
        - task: DotNetCoreCLI@2
          displayName: 'Build project'
          inputs:
            projects: 'src/Theatreers.Show/Theatreers.Show.csproj'
            arguments: '--output $(dotnetBuildOutputPath) --configuration Release'
        # Execute the Sonar Cloud Analysis, and push to Sonar Cloud
        - task: SonarSource.sonarcloud.ce096e50-6155-4de8-8800-4221aaeed4a1.SonarCloudAnalyze@1
          displayName: 'Run Code Analysis'
- stage: 'PR_Build'
  dependsOn: []
  condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'))
  displayName: 'PR Build from Feature into Master'
  jobs:
    - job: 'build'
      displayName: 'PR Build'
      pool:
        name: Hosted Ubuntu 1604
      steps:
      # Setup the Sonar Cloud for analysis
        - task: SonarSource.sonarcloud.14d9cde6-c1da-4d55-aa01-2965cd301255.SonarCloudPrepare@1
          displayName: 'Prepare analysis on SonarCloud'
          inputs:
            SonarCloud: 'Theatreers Sonarcloud'
            organization: 'theatreers'
            projectKey: $(projectName)
            projectName: $(projectName)
        - task: DotNetCoreCLI@2
          displayName: 'Build project'
          inputs:
            projects: 'src/Theatreers.Show/Theatreers.Show.csproj'
            arguments: '--output $(dotnetBuildOutputPath) --configuration Release'
        # Execute the Sonar Cloud Analysis, and push to Sonar Cloud
        - task: SonarSource.sonarcloud.ce096e50-6155-4de8-8800-4221aaeed4a1.SonarCloudAnalyze@1
          displayName: 'Run Code Analysis'
- stage: 'Master_CI_Build'
  dependsOn: []
  displayName: 'Master CI Build'
  jobs:
    - job: 'build'
      displayName: 'Master CI Build'
      pool:
        name: Hosted Ubuntu 1604
      steps:
      # Setup the Sonar Cloud for analysis
        - task: SonarSource.sonarcloud.14d9cde6-c1da-4d55-aa01-2965cd301255.SonarCloudPrepare@1
          displayName: 'Prepare analysis on SonarCloud'
          inputs:
            SonarCloud: 'Theatreers Sonarcloud'
            organization: 'theatreers'
            projectKey: $(projectName)
            projectName: $(projectName)
        - task: DotNetCoreCLI@2
          displayName: 'Build project'
          inputs:
            projects: 'src/Theatreers.Show/Theatreers.Show.csproj'
            arguments: '--output $(dotnetBuildOutputPath) --configuration Release'
        # Execute the Sonar Cloud Analysis, and push to Sonar Cloud
        - task: SonarSource.sonarcloud.ce096e50-6155-4de8-8800-4221aaeed4a1.SonarCloudAnalyze@1
          displayName: 'Run Code Analysis'
        # Zip the files to be published
        - task: ArchiveFiles@2
          displayName: 'Archive files'
          inputs:
            rootFolderOrFile: '$(dotnetBuildOutputPath)'
            includeRootFolder: false
            archiveFile: '$(buildPublishPath)/src/$(Build.BuildId).zip'
        # Copy the template to the deploy folder
        - task: CopyFiles@2
          displayName: 'Copy Files to: $(buildPublishPath)/templates'
          inputs:
            SourceFolder: deploy
            TargetFolder: '$(buildPublishPath)/deploy'
        # Publish the artifacts
        - task: PublishPipelineArtifact@0
          displayName: 'Publish Pipeline Artifact'
          inputs:
            targetPath: '$(buildPublishPath)'
- stage: 'devrelease'
  displayName: 'Microservice Dev Release'
  dependsOn: 'Master_CI_Build'
  variables: 
    artifactsAccountName: 'thmgtdevartifactstg'
    artifactsResourceGroupName: 'th-mgt-dev-rg'
    cosmosDbAccountName: 'th-core-dev-cosmos'
    cosmosDbResourceGroup: 'th-core-dev-rg'
    environmentName: 'dev'
    serviceBusNamespaceResourceGroup: 'th-core-dev-rg'
    servicePrincipalObjectId: '6ee1bb40-e589-4884-90bc-c705d88bb3e0'
    serviceResourceGroupName: 'th-show-dev-rg'
  jobs:
    - job: 'microservicereleaseglobal'
      displayName: 'Microservice Release (Global)'
      pool:
        name: 'Hosted Windows 2019 with VS2019'
      steps:
        - task: DownloadPipelineArtifact@1
          inputs:
            buildType: 'current'
            artifactName: 'drop'
            targetPath: '$(System.DefaultWorkingDirectory)/'
        - task: CmdLine@2
          inputs:
            script: 'ls -la'
        - task: AzureFileCopy@3
          inputs:
            SourcePath: '$(System.DefaultWorkingDirectory)/deploy/apim'
            azureSubscription: 'Theatreers Dev AzureDevOps ServPrin'
            Destination: 'AzureBlob'
            storage: '$(artifactsAccountName)'
            ContainerName: 'templates'
            outputStorageUri: 'templateContainerUri'
            outputStorageContainerSasToken: 'templateContainerSasToken'
        - task: AzureResourceGroupDeployment@2
          inputs:
            azureSubscription: 'Theatreers Dev AzureDevOps ServPrin'
            action: 'Create Or Update Resource Group'
            resourceGroupName: '$(serviceResourceGroupName)'
            location: '$(region)'
            templateLocation: 'Linked artifact'
            csmFile: '$(System.DefaultWorkingDirectory)/deploy/show-global.json'
            overrideParameters: '-templateContainerUri $(templateContainerUri) -templateContainerSasToken $(templateContainerSasToken) -environmentName $(environmentName)'
            deploymentMode: 'Incremental'
    - job: 'microservicereleaseregion'
      displayName: 'Microservice Release (Regional)'
      dependsOn: 'microservicereleaseglobal'
      pool:
        name: 'Hosted Windows 2019 with VS2019'
      variables:
        aadClientId: '73e2635f-dadd-443b-9e47-89ac07f91485'
        aadB2cIssuer: 'https://login.microsoftonline.com/theatreers.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1_SiUpIn'
      strategy:
        matrix: { westeurope: 
          { region: 'West Europe', functionAppName: 'th-show-dev-weu-func', keyvaultName: 'th-show-dev-weu-kv', serviceResourceGroupName: 'th-show-dev-weu-rg' },
          northeurope: { region: 'North Europe', functionAppName: 'th-show-dev-neu-func', keyvaultName: 'th-show-dev-neu-kv', serviceResourceGroupName: 'th-show-dev-neu-rg' } }
      steps:        
        # Setup the Sonar Cloud for analysis
        - task: DownloadPipelineArtifact@1
          inputs:
            buildType: 'current'
            artifactName: 'drop'
            targetPath: '$(System.DefaultWorkingDirectory)/'
        # Copy the files from APIM folder in Git to Storage Account
        - task: AzureFileCopy@3
          inputs:
            SourcePath: '$(System.DefaultWorkingDirectory)/deploy/apim'
            azureSubscription: 'Theatreers Dev AzureDevOps ServPrin'
            Destination: 'AzureBlob'
            storage: '$(artifactsAccountName)'
            ContainerName: 'templates'
            outputStorageUri: 'templateContainerUri'
            outputStorageContainerSasToken: 'templateContainerSasToken'
        # Create the appropriate storage account
        - task: AzureResourceGroupDeployment@2
          inputs:
            azureSubscription: 'Theatreers Dev AzureDevOps ServPrin'
            action: 'Create Or Update Resource Group'
            resourceGroupName: '$(serviceResourceGroupName)'
            location: '$(region)'
            templateLocation: 'Linked artifact'
            csmFile: '$(System.DefaultWorkingDirectory)/deploy/show-regional.json'
            overrideParameters: '-templateContainerUri $(templateContainerUri) -templateContainerSasToken $(templateContainerSasToken) -environmentName $(environmentName) -tenantId $(tenantId) -servicePrincipalObjectId $(servicePrincipalObjectId) -cosmosDbAccountName $(cosmosDbAccountName) -cosmosDbResourceGroup $(cosmosDbResourceGroup) -aadClientId $(aadClientId) -aadB2cIssuer $(aadB2cIssuer)'
            deploymentMode: 'Incremental'
        - task: AzureKeyVault@1
          inputs:
            azureSubscription: 'Theatreers Dev AzureDevOps ServPrin'
            KeyVaultName: '$(keyvaultName)'
        - task: AzureFunctionApp@1
          inputs:
            azureSubscription: 'Theatreers Dev AzureDevOps ServPrin'
            appType: 'functionApp'
            appName: '$(functionAppName)'
            package: '$(System.DefaultWorkingDirectory)/src/*.zip'
            appSettings: '-storageConnectionString $(storageConnectionString) -topicConnectionString $(Connection0) -cosmosConnectionString $(cosmosConnectionString)'
            deploymentMethod: 'auto'