stages:
- stage: CI
  condition: ${{ parameters.condition }}
  
  jobs:
  - template: /pipelines/${{ parameters.service }}/${{ parameters.service }}.ci.yml
    parameters:
      buildOutputPath: '$(Build.ArtifactStagingDirectory)/build-output/'
      buildPublishPath: '$(Build.ArtifactStagingDirectory)/publish-path/'
      name: "CI"
      environment: ${{ parameters.environment}}
      service: ${{ parameters.service }}
      src: ${{ parameters.src }}