stages:
- stage: CI
  condition: ${{ parameters.condition }}
  jobs:
  - template: /pipelines/${{ parameters.service }}/${{ parameters.service }}.ci.yml
    parameters:
      name: "${{ parameters.service}}_CI"
      environment: ${{ parameters.environment}}
      service: ${{ parameters.service }}