stages:
- stage: dev
  condition: ${{ parameters.condition }}
  jobs:
  - template: /pipelines/${{ parameters.service }}/${{ parameters.service }}.dev.yml
    parameters:
      name: "dev"
      environment: ${{ parameters.environment}}
      service: ${{ parameters.service }}