stages:
- stage: dev
  condition: ${{ parameters.condition }}
  dependsOn: ${{ parameters.dependsOn }}
  jobs:
  - template: /pipelines/${{ parameters.service }}/${{ parameters.service }}.dev.yml
    parameters:
      buildOutputPath: '$(Build.ArtifactStagingDirectory)/build-output/'
      buildPublishPath: '$(Build.ArtifactStagingDirectory)/publish-path/'
      name: "dev"
      environment: ${{ parameters.environment}}
      service: ${{ parameters.service }}
      src: ${{ parameters.src }}