stages:
- template: /pipelines/stages/ci.yml
  parameters:
    condition: and(succeeded(), in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI'), contains(variables['Build.SourceBranch'], 'refs/heads/feature/'))
    environment: ci
    service: ${{ parameters.service }}

- template: /pipelines/stages/dev.yml
  parameters:
    condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'))
    dependsOn: ''
    environment: dev
    service: ${{ parameters.service }}

- template: /pipelines/stages/preprod.yml
  parameters:
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'), in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI'))
    dependsOn: dev
    environment: preprod
    service: ${{ parameters.service }}

- template: /pipelines/stages/prod.yml
  parameters:
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'), in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI'))
    dependsOn: preprod
    environment: prod
    service: ${{ parameters.service }}