stages:
- stage: master
  condition: ${{ parameters.condition }}
  dependsOn: ${{ parameters.dependsOn }}
  jobs:
  - template: /pipelines/${{ parameters.service }}/${{ parameters.service }}.master.yml
    parameters:
      artifactName: ${{ parameters.artifactName }}
      buildOutputPath: '$(Build.ArtifactStagingDirectory)/build-output/'
      buildPublishPath: '$(Build.ArtifactStagingDirectory)/publish-path/'
      name: "master"
      environment: ${{ parameters.environment}}
      service: ${{ parameters.service }}
      src: ${{ parameters.src }}