stages:
  - ${{ each region in parameters.regions }}:
    - stage: "preprod_${{ region.long }}"
      condition: ${{ parameters.condition }}
      dependsOn: ${{ parameters.dependsOn }}
      jobs:
      - template: /pipelines/${{ parameters.service }}/${{ parameters.service }}.preprod.yml
        parameters:
          artifactName: ${{ parameters.artifactName }}
          azureServiceGroupName: ${{ parameters.azureServiceGroupName }}
          buildOutputPath: '$(Build.ArtifactStagingDirectory)/build-output/'
          buildPublishPath: '$(Build.ArtifactStagingDirectory)/publish-path/'
          name: "preprod"
          environment: ${{ parameters.environment}}
          region: ${{ region }}
          service: ${{ parameters.service }}
          src: ${{ parameters.src }}