stages:
- stage: preprod
  condition: ${{ parameters.condition }}
  jobs:
  - template: /pipelines/${{ parameters.service }}/${{ parameters.service }}.preprod.yml
    parameters:
      name: "preprod"
      environment: ${{ parameters.environment}}
      service: ${{ parameters.service }}