stages:
  - ${{ each region in parameters.regions }}:
    - stage: "prod_${{ region.long }}"
      condition: ${{ parameters.condition }}
      dependsOn: "${{ parameters.dependsOn }}_${{ regions.*.long }}"
      jobs:
        - template: /pipelines/${{ parameters.service }}/${{ parameters.service }}.prod.yml
          parameters:
            artifactName: ${{ parameters.artifactName }}
            azureServiceGroupName: ${{ parameters.azureServiceGroupName }}
            name: "prod"
            environment: ${{ parameters.environment}}
            region: ${{ region }}
            service: ${{ parameters.service }}
            src: ${{ parameters.src }}