jobs:
  - job: ${{ parameters.name }}
    steps:
    - task: CmdLine@2
      inputs:
        script: |
          echo "Hello ${{ parameters.environment }}"
          #test something
          #hello world
          #another test