jobs:
  - job: ${{ parameters.name }}
    pool:
      vmImage: ubuntu-16.04
    steps:
    - task: CmdLine@2
      inputs:
        script: |
          echo "Hello ${{ parameters.environment }}"
          #trigger
          #another trigger