jobs:
  - job: ${{ parameters.name }}
    pool:
      vmImage: ubuntu-16.04
    steps:
    - script: 'echo "Hello ${{ parameters.environment }} -- Thank you for the artifact from ${{ parameters.artifactName }}"'
      displayName: "Hello World"