jobs:
  - job: ${{ parameters.name }}
    pool:
      vmImage: ubuntu-16.04
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
        displayName: 'Install Node.js'
      - script: |
          npm install
          npm run build
      - task: PublishPipelineArtifact@0
        inputs:
          artifactName: '$(artifactName)'
          targetPath: '$(System.DefaultWorkingDirectory)/dist/'