jobs:
  - job: ${{ parameters.name }}
    pool:
      vmImage: ubuntu-16.04
    steps:
    - script: 'echo "Hello ${{ parameters.environment }}"'
      displayName: "Hello World"
      #COmment trigger
      #comment trigger
      #Trigger