jobs:
  - job: ${{ parameters.name }}
    pool:
      vmImage: ubuntu-16.04
    steps:
      - powershell: |
        Install-Module -Name Pester -Force -Verbose -Scope CurrentUser 
        Import-Module Pester
        Invoke-Pester -Script @{Path ='deploy/builidingblocks/arm-template-tests.ps1'; Parameters = @{folder = './deploy/' }} -OutputFile TEST-CoreArmTemplates.xml -OutputFormat NUnitXml
        displayName: 'Execute PESTER Tests'
      - task: PublishTestResults@2
        displayName: 'Publish Test Results **/*.xml'
        inputs:
          testResultsFormat: NUnit
          testResultsFiles: 'TEST-*.xml'