jobs:
  - deployment: ${{ parameters.name }}
    pool:
      vmImage: ubuntu-16.04
    environment: "th-${{ parameters.azureServiceGroupName}}-${{ parameters.environment }}-${{ parameters.region.short }}"
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self
            - task: gittools.gitversion.gitversion-task.GitVersion@5
              displayName: GitVersion 
              inputs: 
                preferBundledVersion: false            
            - task: DotNetCoreCLI@2
              displayName: "Restore project"
              inputs:
                command: "restore"
                projects: "src/${{ parameters.service }}/${{ parameters.service }}.csproj"
                feedsToUse: "select"
                vstsFeed: "fa1af919-202e-4e5c-91a7-dafe6f7d519e"
            - task: DotNetCoreCLI@2
              displayName: 'dotnet pack' 
              inputs: 
                command: pack
                packagesToPack: "src/${{ parameters.service }}/${{ parameters.service }}.csproj"
                nobuild: true 
                versioningScheme: byEnvVar 
                versionEnvVar: GitVersion.NuGetVersion
            - task: DotNetCoreCLI@2 
              displayName: 'dotnet nuget push' 
              inputs: 
                command: push 
                publishVstsFeed: '168c2416-9cd1-4e62-e89vb-5665da67a44c' 
                versioningScheme: byBuildNumber
