jobs:
  - job: ${{ parameters.name }}
    pool:
      vmImage: ubuntu-16.04
    steps:
      - script: 'echo "Hello ${{ parameters.environment }}"'
        displayName: "Hello World"
        #random commit test