variables:
  artifactName: "drop"
  applicationServiceNameFull: "Theatreers.Show"
  applicationServiceNameShort: "Show"
  azureServiceGroupName: "show"
  src: "src/Theatreers.Show/"
  system.debug: true

trigger:
  branches:
    include:
    - master
    - feature/*
  paths:
    include:
    - src/Theatreers.Show/*
    - /pipelines/Theatreers.Show.yml
    - /pipelines/Theatreers.Show/*
pr:
  branches:
    include:
    - master
    - feature/*
  paths:
    include:
    - src/Theatreers.Show/*
    - /pipelines/Theatreers.Show.yml
    - /pipelines/Theatreers.Show/*

stages:
  - template: /pipelines/stages/lifecycle.yml
    parameters:
      artifactName: ${{ variables.artifactName }}
      azureServiceGroupName: ${{ variables.azureServiceGroupName }}
      regions: [
        { "short": "weu", "long": "westeurope"}
      ]
      service: ${{ variables.applicationServiceNameFull }}
      src: ${{ variables.src }}