variables:
  artifactName: 'drop'
  service: Theatreers.Frontend
  src: "src/Theatreers.Frontend/"
  system.debug: true

trigger:
  branches:
    include:
    - master
    - feature/*
  paths:
    include:
    - src/Theatreers.Frontend/*
    - /pipelines/Theatreers.Frontend.yml
    - /pipelines/Theatreers.Frontend/*
pr:
  branches:
    include:
    - master
    - feature/*
  paths:
    include:
    - src/Theatreers.Frontend/*
    - /pipelines/Theatreers.Frontend.yml
    - /pipelines/Theatreers.Frontend/*

stages:
- template: /pipelines/stages/lifecycle.yml
  parameters:
    artifactName: ${{ variables.artifactName }}
    service: ${{ variables.service }}
    src: ${{ variables.src }}