stages:
- stage: 'Core_Dev_Regional'
  variables:
    environmentName: 'dev'
    managementResourceGroupName: 'th-mgt-dev-rg'
    managementStorageAccountName: 'thmgtdevartifactstg'
  dependsOn: []
  displayName: 'Core - Dev (Regional)'
  jobs:
    - job: 'Core_Dev_Regional_Job'
      displayName: 'Core - Dev (Regional) Job'
      pool:
        name: 'Hosted Windows 2019 with VS2019'
      strategy:
        matrix: 
          { 
          westeurope: { namingPrefix: 'th-core-dev-weu', region: 'West Europe', resourceGroupName: 'th-core-dev-weu-rg'  },
          northeurope: { namingPrefix: 'th-core-dev-neu', region: 'North Europe', resourceGroupName: 'th-core-dev-neu-rg'  }
          }
        maxParallel: 1
      steps:
      - template: templates/core-region-steps.yaml
- stage: 'Core_Dev_Global'
  variables:
    environmentName: 'dev'
    managementResourceGroupName: 'th-mgt-dev-rg'
    managementStorageAccountName: 'thmgtdevartifactstg'
    namingPrefix: 'th-core-dev'
    region: 'West Europe'
    resourceGroupName: 'th-core-dev-rg'
  dependsOn: []
  displayName: 'Core - Dev (Global)'
  jobs:
    - job: 'Core_Dev_Global_Job'
      displayName: 'Core - Dev (Global) Job'
      pool:
        name: 'Hosted Windows 2019 with VS2019'
      steps:
      - template: templates/core-global-steps.yaml

