# cert-manager/certificate.yaml
kind: Certificate
apiVersion: certmanager.k8s.io/v1alpha1
metadata:
  name: dev-theatreers-com
spec:
  secretName: dev-theatreers-com-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: dev.theatreers.com
  dnsNames:
  - dev.theatreers.com
  #- api.dev.theatreers.com
  - function.dev.theatreers.com
  acme:
    config:
    - dns01:
        ingress: theatreers-ingress
        provider: AzureDNS
      domains:
      - dev.theatreers.com
      #- api.dev.theatreers.com
      - function.dev.theatreers.com