apiVersion: apps/v1
kind: Deployment
metadata:
  name: theatreers-frontend-deployment
  labels:
    app: theatreers-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: theatreers-frontend
  template:
    metadata:
      labels:
        app: theatreers-frontend
    spec:
      containers:
      - name: theatreers-frontend
        image: #{containerRegistry}#.azurecr.io/frontend:latest
        imagePullPolicy: "Always"
        resources:
          limits:
            cpu: 125m
            memory: 250Mi
          requests:
            cpu: 75m
            memory: 150Mi
        ports:
        - containerPort: 80
        env:          
        - name: AzureAdB2C__ClientId
          valueFrom:
            secretKeyRef:
              name: #{podSecretReference}#
              key: AzureAdB2C__ClientId
        - name: AzureConnections__dpBlobStgConnectionString
          valueFrom:
            secretKeyRef:
              name: #{podSecretReference}#
              key: AzureConnections__dpBlobStgConnectionString
        - name: AzureConnections__spClientId
          valueFrom:
            secretKeyRef:
              name: #{podSecretReference}#
              key: AzureConnections__spClientId
        - name: AzureConnections__spClientKey
          valueFrom:
            secretKeyRef:
              name: #{podSecretReference}#
              key: AzureConnections__spClientKey
        - name: AzureConnections__kvName
          valueFrom:
            secretKeyRef:
              name: #{podSecretReference}#
              key: AzureConnections__kvName
        - name: AzureConnections__aadTenant
          valueFrom:
            secretKeyRef:
              name: #{podSecretReference}#
              key: AzureConnections__aadTenant
        - name: AzureConnections__frontendDpKeyReference
          valueFrom:
            secretKeyRef:
              name: #{podSecretReference}#
              key: AzureConnections__frontendDpKeyReference
        - name: AzureAdB2C__Domain
          valueFrom:
            configMapKeyRef:
              name: #{podConfigReference}#
              key: AzureAdB2C__Domain
        - name: AzureAdB2C__SignUpSignInPolicyId
          valueFrom:
            configMapKeyRef:
              name: #{podConfigReference}#
              key: AzureAdB2C__SignUpSignInPolicyId
        - name: AzureAdB2C__ResetPasswordPolicyId
          valueFrom:
            configMapKeyRef:
              name: #{podConfigReference}#
              key: AzureAdB2C__ResetPasswordPolicyId
        - name: AzureAdB2C__EditProfilePolicyId
          valueFrom:
            configMapKeyRef:
              name: #{podConfigReference}#
              key: AzureAdB2C__EditProfilePolicyId
        - name: ApplicationInsights__InstrumentationKey
          valueFrom:
            configMapKeyRef:
              name: #{podConfigReference}#
              key: ApplicationInsights__InstrumentationKey
        - name: cdn__url
          valueFrom:
            configMapKeyRef:
              name: #{podConfigReference}#
              key: cdn__url
---
apiVersion: v1
kind: Service
metadata:
  name: theatreers-frontend-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: theatreers-frontend